---
- name: gem install oauth-plugin
  become: yes
  become_user: redmine
  gem:
    name: oauth-plugin
    state: present

- name: Download redmine_oauth_provider (for Redmine 3.x.x)
  become: yes
  become_user: redmine
  git:
    repo: https://github.com/suer/redmine_oauth_provider.git
    dest: ~/redmine/plugins/redmine_oauth_provider
    update: no
    version: HEAD
  when: redmine_version | version_compare('3.0.0', '>=')

- name: Download redmine_oauth_provider (for Redmine 2.x.x)
  become: yes
  become_user: redmine
  git:
    repo: https://github.com/suer/redmine_oauth_provider.git
    dest: ~/redmine/plugins/redmine_oauth_provider
    update: no
    version: 0.0.3
  when: redmine_version | version_compare('3.0.0', '<')

- name: Template redmine_oauth_provider/redmine_oauth_provider.rb
  become: yes
  become_user: redmine
  template: src=redmine_oauth_provider/redmine_oauth_provider.rb dest=~/redmine/config/initializers/redmine_oauth_provider.rb mode=0644
  tags: test

- name: Bundle install
  become: yes
  become_user: redmine
  command: "chdir=~/redmine bundle install --without development test"

- name: Run rake
  become: yes
  become_user: redmine
  command: "chdir=~/redmine bundle exec rake redmine:plugins:migrate RAILS_ENV=production"

- name: Restart redmine
  become: yes
  service: name=redmine state=restarted
