# redmine

- name: Delete redmine-{{ redmine_version }}
  file: path=~/redmine state=absent
  remote_user: redmine

- name: Download redmine
  get_url: url=http://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz dest=~/redmine-{{ redmine_version }}.tar.gz
  remote_user: redmine

- name: Extract tar.gz
  shell: tar zxvf redmine-{{ redmine_version }}.tar.gz chdir=~
  remote_user: redmine

- name: Move redmine-{{ redmine_version }} to redmine
  shell: mv redmine-{{ redmine_version }} redmine chdir=~
  remote_user: redmine

- name: Template config/database.yml for PosgreSQL
  template: src=database.yml dest=~/redmine/config/database.yml mode=0600
  remote_user: redmine

# unicorn
- name: Template Gemfile.local
  template: src=Gemfile.local dest=~/redmine/Gemfile.local mode=0644
  remote_user: redmine

- name: Template config/unicorn.rb
  template: src=unicorn.rb.j2 dest=~/redmine/config/unicorn.rb mode=0600
  remote_user: redmine

- name: mkdir redmine/tmp/pids
  become: yes
  become_user: redmine
  file: path=~/redmine/tmp/pids state=directory owner=redmine group=redmine mode=0775

# bundle install
- name: set jobs 4
  shell: bundle config --global --jobs 4 chdir=~/redmine
  remote_user: redmine

- name: Install pg
  shell: bundle config build.pg --with-pg-config=/usr/pgsql-9.4/bin/pg_config chdir=~/redmine
  remote_user: redmine

- name: Install Bundle
  shell: bundle install --path vendor/bundle --without development test chdir=~/redmine
  remote_user: redmine

#Initialize Secret Token
- name: Initialize Secret Token
  shell: bundle exec rake generate_secret_token chdir=~/redmine
  remote_user: redmine

# Initialize Database
- yum:
    name: python-psycopg2
    state: latest
  become: yes

- postgresql_user: name=redmine
                   password=redmine
                   role_attr_flags=NOINHERIT
  become: yes
  become_user: postgres

- postgresql_db: name=redmine
                 encoding='UTF-8'
                 owner=redmine
                 lc_collate='ja_JP.UTF-8'
                 lc_ctype='ja_JP.UTF-8'
                 template='template0'
  become: yes
  become_user: postgres

- name: Initialize Database
  shell: "bundle exec rake db:migrate RAILS_ENV=production chdir=~/redmine"
  remote_user: redmine

- name: Load Default Data for Japanese
  shell: "bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=ja chdir=~/redmine"
  remote_user: redmine

# Add Redmine as service
- name: Template nginx/conf.d/redmine.conf
  become: yes
  template: src=nginx_redmine.conf.j2 dest=/etc/nginx/conf.d/redmine.conf mode=0644

# Add Config for Redmine
- name: Template /etc/init.d/redmine
  become: yes
  template: src=init_redmine.j2 dest=/etc/init.d/redmine mode=0755 owner=root group=root

- name: ensure redmine is running automatically at boot time
  become: yes
  service: name=redmine state=started enabled=yes

- name: restart nginx
  become: yes
  service: name=nginx state=restarted
