---

- name: Redmineがインストールされているかどうかを確認します。
  stat:
    path: "{{ redmine_home }}"
  register: redmine_install_dir

- name: Redmineのインストールに必要なライブラリをインストールします。
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "@Development Tools"
    - openssl-devel
    - readline-devel
    - zlib-devel
    - curl-devel
    - libyaml-devel
    - libffi-devel
    - ImageMagick
    - ImageMagick-devel
    - ipa-pgothic-fonts

- name: Redmineのインストールディレクトリを作成します。
  become: yes
  file:
    # HACK: https://github.com/ansible/ansible-modules-core/issues/2936
    path: "{{ redmine_home }}/redmine-{{ redmine_version }}"
    owner: "{{ redmine_user_name }}"
    group: "{{ redmine_group_name }}"
    state: directory
  when: not redmine_install_dir.stat.exists

- name: Redmine {{ redmine_version }} をダウンロードします。
  become: yes
  become_user: "{{ redmine_user_name }}"
  unarchive:
    src: http://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz
    dest: "{{ redmine_home }}"
    creates: "{{ redmine_home }}/Gemfile"
    extra_opts: --strip-components=1
    copy: no
  # HACK: https://github.com/ansible/ansible-modules-core/issues/2936
  environment:
    LANG: "C"
    LC_ALL: "C"
    LC_MESSAGES: "C"
  when: not redmine_install_dir.stat.exists

- name: Redmineのデータベース設定を配置します。
  become: yes
  become_user: "{{ redmine_user_name }}"
  template:
    src: database.yml
    dest: "{{ redmine_home }}/config/database.yml"
    mode: 0600
  when: not redmine_install_dir.stat.exists

# unicorn
- name: Unicornインストール用のGemfileを配置します。
  become: yes
  become_user: "{{ redmine_user_name }}"
  template:
    src: Gemfile.local
    dest: "{{ redmine_home }}/Gemfile.local"
    mode: 0644
  when: not redmine_install_dir.stat.exists

- name: Template config/unicorn.rb
  become: yes
  become_user: "{{ redmine_user_name }}"
  template:
    src: unicorn.rb.j2
    dest: "{{ redmine_home }}/config/unicorn.rb"
    mode: 0600
  when: not redmine_install_dir.stat.exists

- name: mkdir redmine/tmp/pids
  become: yes
  become_user: "{{ redmine_user_name }}"
  file:
    path: "{{ redmine_home }}/tmp/pids"
    state: directory
    mode: 0775
  when: not redmine_install_dir.stat.exists

# bundle install
- name: set jobs 4
  become: yes
  become_user: "{{ redmine_user_name }}"
  shell:
    . ~/.bashrc && {{ item }}
    chdir={{ redmine_home }}
  with_items:
    - bundle config --global --jobs 4
    - bundle config build.pg --with-pg-config=/usr/pgsql-9.4/bin/pg_config
    - bundle install --without development test
    - bundle exec rake generate_secret_token
    - bundle exec rake db:migrate
    - bundle exec rake redmine:load_default_data
  environment:
    RAILS_ENV: production
    REDMINE_LANG: ja
#  when: not redmine_install_dir.stat.exists

# Add Config for Redmine
- name: Template /etc/init.d/redmine
  become: yes
  template:
    src: init_redmine.j2
    dest: /etc/init.d/redmine
    mode: 0755
    owner: root
    group: root
  when: not redmine_install_dir.stat.exists

- name: ensure redmine is running automatically at boot time
  become: yes
  service:
    name: redmine
    state: restarted
    enabled: yes
  when: not redmine_install_dir.stat.exists

- include: plugins/redmine_backlogs.yml
- include: plugins/redmine_absolute_dates.yml
- include: plugins/redmine_oauth_provider.yml
