---
- name: グループ {{ group_name }} を作成します。
  become: yes
  group:
    name: "{{ group_name }}"
    state: present

- name: ユーザー {{ user_name }} を作成します。
  become: yes
  user:
    name: "{{ user_name }}"
    group: "{{ group_name }}"
    state: present

- name: sudo権限を追加します。
  become: yes
  template:
    src: "{{ sudoers }}"
    dest: /etc/sudoers.d/{{ user_name }} mode=0440
  when: sudoers is defined
