- name: rbenvがインストールされているか確認します。
  become_user: redmine
  stat:
    path: ~/.rbenv
  register: rbenv

- name: Download rbenv
  become_user: redmine
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
  when: rbenv.stat.exists == false

- name: Update rbenv
  become_user: redmine
  command:
    git pull
    chdir=~/.rbenv
  when: rbenv.stat.exists

- name: rbenv echo
  become_user: redmine
  command: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
  when: rbenv.stat.exists == false

- name: rbenv echo
  become_user: redmine
  command: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
  when: rbenv.stat.exists == false

- name: ruby-buildがインストールされているか確認します。
  become_user: redmine
  stat:
    path: ~/.rbenv/plugins/ruby-build
  register: ruby_build

- name: Download ruby-build
  become_user: redmine
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  when: ruby_build.stat.exists == false

- name: Install ruby-build
  become_user: redmine
  command:
    /bin/bash -c "export PREFIX=~/local/src/ &&  ~/.rbenv/plugins/ruby-build/install.sh"
    chdir=~/.rbenv/plugins/ruby-build
  when: ruby_build.stat.exists == false

- name: Rubyがインストールされているか確認します。
  become_user: redmine
  stat:
    path: ~/.rbenv/versions/{{ ruby_ver }}
  register: ruby_version

- name: Install Ruby
  become_user: redmine
  command: bash -c "rbenv install {{ ruby_ver }}"
  when: ruby_version.stat.exists == false

- name: rbenv global 
  become_user: redmine
  command: bash -c "rbenv global {{ ruby_ver }}"
  notify: rehash
  when: ruby_version.stat.exists == false

- name: gem install
  become_user: redmine
  command: bash -c "rbenv exec gem install bundler --no-ri --no-rdoc"
  notify: rehash
  when: ruby_version.stat.exists == false
