---

- name: Apacheをインストールします。
  become: yes
  yum:
    name: httpd
    state: latest

- name: Apacheのデフォルト設定ファイルを配置します。
  become: yes
  template:
    src: templates/{{ item }}
    dest: /etc/httpd/{{ item }}
    group: apache
    owner: apache
    mode:  0644
  with_items:
    - conf/httpd.conf
    - conf/magic
    - conf.d/welcome.conf

- name: Apacheのインストール時に配置されている不要なファイルを削除します。
  become: yes
  file:
    path: /etc/httpd/{{ item }}
    state: absent
  with_items:
    - conf.d/README
    - conf.d/autoindex.conf
    - conf.d/perl.conf
    - conf.d/userdir.conf

- name: Apacheが自動起動するように設定し、再起動します。
  become: yes
  service: 
    name: httpd
    enabled: yes
    state: restarted
